// bpm-react/src/App.tsx
import { useEffect, useState } from 'react';
import { cn } from './utils/cn';
import ColorSelector from './components/ColorSelector';
import Joyride from 'react-joyride';
import MainMenu from './components/MainMenu';
import Blinker from './components/Blinker';
import JOYRIDE_STEPS from './constants/joyrideSteps';
import { BLINKER_COLORS, BLINKER_COLORS_2 } from './constants/blinkerColors';

export default function App() {
    const [bpm, setBpm] = useState(140);
    const [beat, setBeat] = useState(true);
    const [canRunTutorial, setCanRunTutorial] = useState(false);
    const [offBeat, setOffBeat] = useState(false);
    const [isBlinking, setIsBlinking] = useState(false);
    const [colorIndex, setColorIndex] = useState([0, 0]);
    const [split, setSplit] = useState<number>(1);
    const [colorSelectorOpen, setColorSelectorOpen] = useState<
        boolean | number
    >(false);
    const [menuVisible, setMenuVisible] = useState(true);
    const [randomizeColors, setRandomizeColors] = useState(false);

    useEffect(() => {
        setCanRunTutorial(localStorage.getItem('visitedPreviously') !== 'true');
        setTimeout(
            () => localStorage.setItem('visitedPreviously', 'true'),
            10000
        );
    }, []);

    useEffect(() => {
        const interval = setInterval(
            () => {
                if (isBlinking) {
                    setColorIndex((old) => {
                        let index1 = old[0];
                        let index2 = old[1];

                        if (randomizeColors) {
                            const newIndex1 = Math.floor(
                                Math.random() * BLINKER_COLORS.length
                            );
                            let newIndex2 = Math.floor(
                                Math.random() * BLINKER_COLORS_2.length
                            );
                            if (
                                BLINKER_COLORS[newIndex1] ===
                                BLINKER_COLORS_2[newIndex2]
                            ) {
                                newIndex2 = newIndex2 - 1;
                            }
                            index1 = newIndex1;
                            index2 = newIndex2;
                        }
                        return [index1, index2];
                    });

                    setBeat(true);
                    setTimeout(
                        () => {
                            setBeat(false);
                        },
                        (60 / bpm) * 250
                    );

                    setTimeout(
                        () => {
                            setOffBeat(true);
                        },
                        (60 / bpm) * 500
                    );
                    setTimeout(
                        () => {
                            setOffBeat(false);
                        },
                        (60 / bpm) * 750
                    );
                }
            },
            (60 / bpm) * 1000
        );

        return () => clearInterval(interval);
    }, [bpm, isBlinking, randomizeColors]);

    return (
        <div
            className={cn('flex h-full w-full flex-col items-center')}
            style={{ backgroundColor: 'black' }}>
            <button
                onClick={() => setMenuVisible((v) => !v)}
                className={cn('flex h-full w-full items-center justify-center')}
                id="button-main"
                tabIndex={-1}>
                <Blinker
                    isBlinking={isBlinking && !colorSelectorOpen}
                    beat={beat}
                    offBeat={offBeat}
                    split={split}
                    color1={BLINKER_COLORS[colorIndex[0]]}
                    color2={BLINKER_COLORS_2[colorIndex[1]]}
                />
            </button>
            {colorSelectorOpen ? (
                <div className="fixed left-0 top-0 z-10 flex h-full w-full flex-col items-center justify-center">
                    <button
                        onClick={() => setColorSelectorOpen(false)}
                        className="fixed left-0 top-0 -z-10 h-full w-full bg-black opacity-30"
                    />

                    <ColorSelector
                        colors={
                            colorSelectorOpen === 1
                                ? BLINKER_COLORS
                                : BLINKER_COLORS_2
                        }
                        onChange={(ci) => {
                            if (colorSelectorOpen === 1) {
                                setColorIndex([ci, colorIndex[1]]);
                            } else {
                                setColorIndex([colorIndex[0], ci]);
                            }
                            setColorSelectorOpen(false);
                        }}
                    />
                </div>
            ) : null}
            {menuVisible ? (
                <MainMenu
                    onColor1Click={() => {
                        setRandomizeColors(false);
                        setColorSelectorOpen(1);
                    }}
                    onColor2Click={() => {
                        setRandomizeColors(false);
                        setColorSelectorOpen(2);
                    }}
                    onRandomizeColorsClick={() => {
                        setRandomizeColors((v) => !v);
                    }}
                    onSplitColorsClick={() => {
                        setSplit((v) => (v === 4 ? 1 : v * 2));
                    }}
                    onBPMChange={(v) => setBpm(v)}
                    onTutorialClick={() => setCanRunTutorial(true)}
                    onBPMMinusClick={() => setBpm((v) => Math.max(1, v - 1))}
                    onPlayClick={() => setIsBlinking((v) => !v)}
                    onBPMPlusClick={() => setBpm((v) => Math.min(3600, v + 1))}
                    randomizeColors={randomizeColors}
                    split={split}
                    bpm={bpm}
                    isBlinking={isBlinking}
                    runTutorial={canRunTutorial}
                />
            ) : null}
            <Joyride
                run={canRunTutorial}
                continuous
                showProgress
                showSkipButton
                styles={{
                    options: {
                        zIndex: 200,
                    },
                    overlay: {
                        backgroundColor: 'rgba(0, 0, 0, 0.5)',
                    },
                }}
                steps={JOYRIDE_STEPS}
            />
        </div>
    );
}

// bpm-vue/src/App.vue
<script lang="ts" setup>
import BpmBlinker from './components/BpmBlinker.vue';
import MainMenu from './components/MainMenu.vue';
import ColorSelector from './components/ColorSelector.vue';
import { watch, ref, onUnmounted } from 'vue';
import { BLINKER_COLORS, BLINKER_COLORS_2 } from './constants/blinkerColors';
import { cn } from './utils/cn';

const isBlinking = ref<boolean>(false);
const bpm = ref<number>(140);
const colorIndex = ref<[number, number]>([0, 0]);
const beat = ref<boolean>(false);
const offBeat = ref<boolean>(false);
const randomizeColors = ref<boolean>(false);
const split = ref<number>(1);
const canRunTutorial = ref<boolean>(false);
const colorSelectorOpen = ref<number | false>(false);
const menuVisible = ref<boolean>(true);

canRunTutorial.value = localStorage.getItem('visitedPreviously') !== 'true';

setTimeout(() => localStorage.setItem('visitedPreviously', 'true'), 10000);

let interval: number = 0;

watch([bpm, isBlinking], () => {
  if (interval) {
    clearInterval(interval);
  }

  interval = setInterval(
    () => {
      if (isBlinking.value) {
        let index1 = colorIndex.value[0];
        let index2 = colorIndex.value[1];

        if (randomizeColors.value) {
          const newIndex1 = Math.floor(Math.random() * BLINKER_COLORS.length);
          let newIndex2 = Math.floor(Math.random() * BLINKER_COLORS_2.length);
          if (BLINKER_COLORS[newIndex1] === BLINKER_COLORS_2[newIndex2]) {
            newIndex2 = newIndex2 - 1;
          }
          index1 = newIndex1;
          index2 = newIndex2;
        }
        colorIndex.value = [index1, index2];

        beat.value = true;
        setTimeout(
          () => {
            beat.value = false;
          },
          (60 / bpm.value) * 250
        );

        setTimeout(
          () => {
            offBeat.value = true;
          },
          (60 / bpm.value) * 500
        );
        setTimeout(
          () => {
            offBeat.value = false;
          },
          (60 / bpm.value) * 750
        );
      }
    },
    (60 / bpm.value) * 1000
  );

  return () => {
    if (interval) {
      clearInterval(interval);
    }
  };
});

onUnmounted(() => {
  if (interval) {
    clearInterval(interval);
  }
});
</script>

<template>
  <div
    :class="cn('flex h-full w-full flex-col items-center justify-center')"
    :style="{ backgroundColor: 'black' }">
    <button
      @click="menuVisible = !menuVisible"
      :class="cn('flex h-full w-full items-center justify-center')"
      id="button-main"
      tabIndex="{-1}">
      <bpm-blinker
        :is-blinking="isBlinking && !colorSelectorOpen"
        :beat="beat"
        :off-beat="offBeat"
        :split="split"
        :color1="BLINKER_COLORS[colorIndex[0]]"
        :color2="BLINKER_COLORS_2[colorIndex[1]]" />
    </button>
    <div
      v-if="colorSelectorOpen"
      class="fixed left-0 top-0 z-10 flex h-full w-full flex-col items-center justify-center">
      <button
        @click="colorSelectorOpen = false"
        class="fixed left-0 top-0 -z-10 h-full w-full bg-black opacity-30" />
      <color-selector
        :colors="colorSelectorOpen === 1 ? BLINKER_COLORS : BLINKER_COLORS_2"
        @change="
          (ci: number) => {
            if (colorSelectorOpen === 1) {
              colorIndex = [ci, colorIndex[1]];
            } else {
              colorIndex = [colorIndex[0], ci];
            }
            colorSelectorOpen = false;
          }
        " />
    </div>
    <main-menu
      v-if="menuVisible"
      @color1-click="
        () => {
          randomizeColors = false;
          colorSelectorOpen = 1;
        }
      "
      @color2-click="
        () => {
          randomizeColors = false;
          colorSelectorOpen = 2;
        }
      "
      @randomize-colors-click="randomizeColors = !randomizeColors"
      @split-click="
        () => {
          split = split === 4 ? 1 : split * 2;
        }
      "
      @bpm-change="(v) => (bpm = Math.max(1, Math.min(v, 3600)))"
      @tutorial-click="canRunTutorial = true"
      @play="isBlinking = !isBlinking"
      :randomize-colors="randomizeColors"
      :split="split"
      :bpm="bpm"
      :is-blinking="isBlinking"
      :run-tutorial="canRunTutorial" />
  </div>
</template>
